Repository BuildForSDG/team-001-frontend, pull requests merged in 2020-05, with the labels that each got.

#6 First test on pull request. Minor edit
  betalife-app/public/index.html
Labels: good first issue

#8 Add a Codacy badge to README.md
  README.md
Labels: enhancement

#11 Fixed syntax bug
  betalife-app/package-lock.json
  betalife-app/package.json
  betalife-app/src/App.js
  betalife-app/src/components/Intro.js
  betalife-app/src/components/Login.js
Labels: enhancement

#19 Fixed Bug
  betalife-app/src/App.js
  betalife-app/src/components/Events.js
  betalife-app/src/components/Intro.js
  betalife-app/src/images/butterfly_bg.jpg
  betalife-app/src/images/event_bg1.jpg
Labels: bug

#20 Added Event Details UI
  betalife-app/src/App.js
  betalife-app/src/components/EventDetails.js
  betalife-app/src/components/Events.js
Labels: enhancement
